"""Behavior tests for .github/scripts/release-readiness.sh.

The script cuts a release by pushing the release commit straight to the branch it
checked out. Two properties hold that path honest, and both are asserted here from
observable behavior: the process exit code, stdout and stderr, the
GITHUB_STEP_SUMMARY file, the argv the stubbed `gh` recorded, and the state of a
REAL bare git repository the script pushes to.

1. A model verdict is required. Every rung of the credential ladder in
   bin/lib/release-model-call.bash can be missing or rejected. The run then cuts
   nothing and fails, because nobody reviews this cut before it ships.
2. A push the branch rules refuse is a configuration error. The script says which
   credential needs which grant, and it does not retry the identical refusal.

`curl` is stubbed because the Anthropic API is paid. `gh` is stubbed because the
GitHub API needs a credential. Git is real: origin is a bare repository in the
test's own tmp_path, so every claim about what the release pushed is read back
from it.
"""

import os
import shutil
import subprocess
from pathlib import Path

import pytest

from tests._helpers import REPO_ROOT, commit_all, git_env, init_test_repo

pytestmark = pytest.mark.skipif(
    (shutil.which("node") is None or shutil.which("jq") is None)
    and not os.environ.get("CI"),
    reason="node/jq not available (CI runners must have them: skipping there would silently drop this suite)",
)

CREDENTIAL_VARS = (
    "ANTHROPIC_API_KEY",
    "CLAUDE_CODE_OAUTH_TOKEN",
    "CLAUDE_CODE_OAUTH_TOKEN_FALLBACK",
    "CLAUDE_CODE_OAUTH_TOKEN_FALLBACK_3",
    "CLAUDE_CODE_OAUTH_TOKEN_FALLBACK_5",
)

NO_VERDICT_ERROR = "::error title=Release readiness has no model verdict::"

CHANGELOG = """# Changelog

## Unreleased

<!-- New releases are inserted below by scripts/assemble-changelog.mjs; do not edit this file by hand. -->

## [1.0.0] - 2025-01-01

### Added

- Initial release.
"""

# A well-formed Anthropic tool_use response: exactly the shape release-readiness.sh
# digs `should_release` / `recommended_bump` / `rationale` out of.
MODEL_RATIONALE = "Six user-facing fixes have piled up since the last tag."


def _healthy_body(bump: str = "patch") -> str:
    return (
        '{"stop_reason":"tool_use","content":[{"type":"tool_use","name":"release_decision",'
        '"input":{"should_release":true,"recommended_bump":"' + bump + '",'
        '"rationale":"' + MODEL_RATIONALE + '"}}]}'
    )


HEALTHY_BODY = _healthy_body()

NO_RELEASE_BODY = (
    '{"stop_reason":"tool_use","content":[{"type":"tool_use","name":"release_decision",'
    '"input":{"should_release":false,"recommended_bump":"patch",'
    '"rationale":"One doc tweak is not worth a release."}}]}'
)

REJECTED_BODY = (
    '{"error":{"type":"authentication_error","message":"invalid x-api-key"}}'
)

INVOCATION_SEP = "\x01"


def _write_stub(path: Path, body: str) -> None:
    path.write_text(f"#!/usr/bin/env bash\n{body}", encoding="utf-8")
    path.chmod(0o755)


def _install_gh_stub(bin_dir: Path, gh_log: Path, open_release_pr: str = "") -> None:
    """A `gh` that records every invocation's argv (NUL-delimited, invocations
    separated by \\x01) and answers the two calls the release path makes: the
    `release` label create, and the concurrent-release probe. OPEN_RELEASE_PR is
    what `gh pr list` prints, so "" means no release PR is open."""
    _write_stub(
        bin_dir / "gh",
        f'printf "%s\\0" "$@" >> "{gh_log}"\n'
        f'printf "{INVOCATION_SEP}" >> "{gh_log}"\n'
        'case "$1 $2" in\n'
        f'"pr list") printf "%s" "{open_release_pr}" ;;\n'
        "esac\n"
        "exit 0\n",
    )


def _install_curl_stub(bin_dir: Path, status: str, body: str) -> None:
    """A `curl` honouring `-o <file>` (where the response body lands) and printing
    the HTTP status on stdout — exactly what `-w "%{http_code}"` yields."""
    body_file = bin_dir / "curl_body.json"
    body_file.write_text(body, encoding="utf-8")
    _write_stub(
        bin_dir / "curl",
        "out=''\nprev=''\n"
        'for arg in "$@"; do\n'
        '  [[ "$prev" == "-o" ]] && out="$arg"\n'
        '  prev="$arg"\n'
        "done\n"
        f'[[ -n "$out" ]] && cat "{body_file}" > "$out"\n'
        f"printf '%s' '{status}'\n",
    )


def _git(repo: Path, *args: str) -> str:
    done = subprocess.run(
        ["git", "-C", str(repo), *args],
        env=git_env(),
        capture_output=True,
        text=True,
        check=True,
    )
    return done.stdout.strip()


def _make_repo(
    tmp_path: Path, fragments: dict[str, str], open_release_pr: str = ""
) -> tuple[Path, Path, Path, Path]:
    """A sandbox repo carrying real copies of the script under test and everything
    it sources/executes, plus a real bare origin the seed commit is pushed to.
    Returns (repo, origin, gh_log, bin_dir)."""
    repo = tmp_path / "repo"
    init_test_repo(repo)

    scripts = repo / ".github" / "scripts"
    scripts.mkdir(parents=True)
    shutil.copy2(REPO_ROOT / ".github" / "scripts" / "release-readiness.sh", scripts)
    (scripts / "release-readiness.sh").chmod(0o755)

    libdir = repo / "bin" / "lib"
    libdir.mkdir(parents=True)
    shutil.copy2(REPO_ROOT / "bin" / "lib" / "release-model-call.bash", libdir)

    (repo / "scripts").mkdir()
    shutil.copy2(REPO_ROOT / "scripts" / "assemble-changelog.mjs", repo / "scripts")
    shutil.copy2(REPO_ROOT / "scripts" / "pin-readme-rev.mjs", repo / "scripts")

    # A README with a consumer `rev:` pin, so the release path's pin step runs
    # for real here rather than taking its missing-file exit.
    (repo / "README.md").write_text(
        "# x\n\n```yaml\n- repo: x\n  rev: v1.0.0\n```\n", encoding="utf-8"
    )
    (repo / "package.json").write_text(
        '{"name": "x", "version": "1.0.0"}\n', encoding="utf-8"
    )
    (repo / "CHANGELOG.md").write_text(CHANGELOG, encoding="utf-8")
    fragdir = repo / "changelog.d"
    fragdir.mkdir()
    for name, text in fragments.items():
        (fragdir / name).write_text(text, encoding="utf-8")

    origin = tmp_path / "origin.git"
    subprocess.run(["git", "init", "-q", "--bare", str(origin)], check=True)
    commit_all(repo, "seed")
    _git(repo, "remote", "add", "origin", str(origin))
    _git(repo, "push", "-q", "origin", "HEAD")

    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    gh_log = tmp_path / "gh.log"
    _install_gh_stub(bin_dir, gh_log, open_release_pr)
    return repo, origin, gh_log, bin_dir


def _run(
    repo: Path, bin_dir: Path, summary: Path, credentials: dict[str, str]
) -> subprocess.CompletedProcess:
    env = git_env()
    for var in CREDENTIAL_VARS:
        env.pop(var, None)
    env.update(credentials)
    env["PATH"] = f"{bin_dir}:{env['PATH']}"
    env["GH_TOKEN"] = "gh-token-stub"
    env["GITHUB_STEP_SUMMARY"] = str(summary)
    # One attempt, no sleep: a rung must not be retried and no test may block.
    env["ANTHROPIC_MAX_ATTEMPTS"] = "1"
    env["ANTHROPIC_RETRY_DELAY"] = "0"
    env["RELEASE_PUSH_RETRY_DELAY"] = "0"
    # Never a real endpoint even if the stub were somehow bypassed.
    env["ANTHROPIC_API_URL"] = "https://api.invalid/v1/messages"
    return subprocess.run(
        ["bash", ".github/scripts/release-readiness.sh"],
        cwd=repo,
        env=env,
        capture_output=True,
        text=True,
    )


def _gh_invocations(gh_log: Path) -> list[list[str]]:
    if not gh_log.exists():
        return []
    calls = []
    for chunk in gh_log.read_text(encoding="utf-8").split(INVOCATION_SEP):
        if not chunk:
            continue
        args = [a for a in chunk.split("\0") if a != ""]
        if args:
            calls.append(args)
    return calls


def _origin_head_subject(origin: Path, branch: str) -> str:
    return _git(origin, "log", "-1", "--format=%s", branch)


def _origin_file(origin: Path, branch: str, path: str) -> str:
    return _git(origin, "show", f"{branch}:{path}")


def _origin_paths(origin: Path, branch: str) -> list[str]:
    listing = _git(origin, "ls-tree", "-r", "--name-only", branch)
    return listing.splitlines()


FIXED_ONLY = {"1.fixed.md": "- Fixed a crash.\n", "2.fixed.md": "- Fixed a typo.\n"}
WITH_ADDED = {"1.fixed.md": "- Fixed a crash.\n", "3.added.md": "- Added a flag.\n"}


def test_a_model_verdict_cuts_the_release_onto_the_checked_out_branch(
    tmp_path: Path,
) -> None:
    """The whole release path, driven for real against a bare origin. The commit
    the run pushes carries the bumped version, the rolled CHANGELOG, the deleted
    fragments and the pinned README — and it lands on the branch the run checked
    out, with no branch and no pull request in between."""
    repo, origin, gh_log, bin_dir = _make_repo(tmp_path, FIXED_ONLY)
    _install_curl_stub(bin_dir, "200", HEALTHY_BODY)
    summary = tmp_path / "summary.md"
    branch = _git(repo, "rev-parse", "--abbrev-ref", "HEAD")

    result = _run(repo, bin_dir, summary, {"ANTHROPIC_API_KEY": "sk-ant-api-dummy"})
    assert result.returncode == 0, result.stdout + result.stderr

    assert _origin_head_subject(origin, branch) == "chore(release): v1.0.1"
    assert '"version": "1.0.1"' in _origin_file(origin, branch, "package.json")
    assert "## [1.0.1] - " in _origin_file(origin, branch, "CHANGELOG.md")
    assert "- Fixed a crash." in _origin_file(origin, branch, "CHANGELOG.md")
    assert "rev: v1.0.1" in _origin_file(origin, branch, "README.md")
    assert [
        p for p in _origin_paths(origin, branch) if p.startswith("changelog.d/")
    ] == []

    # No release branch, and no pull request: the commit IS the release.
    assert _git(repo, "branch", "--list", "auto-release/v1.0.1") == ""
    assert [
        argv for argv in _gh_invocations(gh_log) if argv[:2] == ["pr", "create"]
    ] == []

    summary_text = summary.read_text(encoding="utf-8")
    assert MODEL_RATIONALE in summary_text
    assert f"Cut release `v1.0.1` onto `{branch}`." in summary_text


@pytest.mark.parametrize(
    ("bump", "expected_version"),
    [
        pytest.param("patch", "1.0.1", id="patch"),
        pytest.param("minor", "1.1.0", id="minor"),
    ],
)
def test_the_cut_version_follows_the_models_bump(
    tmp_path: Path, bump: str, expected_version: str
) -> None:
    """The bump the model reports decides the version that lands on origin."""
    repo, origin, _, bin_dir = _make_repo(tmp_path, WITH_ADDED)
    _install_curl_stub(bin_dir, "200", _healthy_body(bump))
    summary = tmp_path / "summary.md"
    branch = _git(repo, "rev-parse", "--abbrev-ref", "HEAD")

    result = _run(repo, bin_dir, summary, {"ANTHROPIC_API_KEY": "sk-ant-api-dummy"})
    assert result.returncode == 0, result.stdout + result.stderr
    assert (
        _origin_head_subject(origin, branch) == f"chore(release): v{expected_version}"
    )


def test_a_no_release_verdict_pushes_nothing(tmp_path: Path) -> None:
    """Non-vacuity for every test above: the same healthy path with
    `should_release=false` leaves origin exactly where the seed commit left it."""
    repo, origin, _, bin_dir = _make_repo(tmp_path, FIXED_ONLY)
    _install_curl_stub(bin_dir, "200", NO_RELEASE_BODY)
    summary = tmp_path / "summary.md"
    branch = _git(repo, "rev-parse", "--abbrev-ref", "HEAD")

    result = _run(repo, bin_dir, summary, {"ANTHROPIC_API_KEY": "sk-ant-api-dummy"})
    assert result.returncode == 0, result.stdout + result.stderr
    assert _origin_head_subject(origin, branch) == "seed"
    assert "**No release recommended yet**" in summary.read_text(encoding="utf-8")


def test_total_credential_outage_cuts_no_release(tmp_path: Path) -> None:
    """With NO credential set at all, nothing judged the release. The run pushes
    nothing and fails, so the workflow's failure step opens the tracking issue."""
    repo, origin, gh_log, bin_dir = _make_repo(tmp_path, FIXED_ONLY)
    _install_curl_stub(bin_dir, "401", REJECTED_BODY)  # never reached: no rung is set
    summary = tmp_path / "summary.md"
    branch = _git(repo, "rev-parse", "--abbrev-ref", "HEAD")

    result = _run(repo, bin_dir, summary, {})
    assert result.returncode == 1, result.stdout + result.stderr
    assert NO_VERDICT_ERROR in result.stdout, result.stdout
    assert "no model verdict, so this run cut no release" in result.stderr, (
        result.stderr
    )
    assert "No release credential is set" in result.stderr, result.stderr

    assert _origin_head_subject(origin, branch) == "seed"
    assert _gh_invocations(gh_log) == []
    assert "No release cut — no model verdict." in summary.read_text(encoding="utf-8")


def test_every_rung_rejected_cuts_no_release_and_names_each_credential(
    tmp_path: Path,
) -> None:
    """All five rungs configured, every one 401'd. Nothing is pushed, and the log
    accounts for each rejected rung BY VARIABLE NAME (never by value)."""
    repo, origin, _, bin_dir = _make_repo(tmp_path, FIXED_ONLY)
    _install_curl_stub(bin_dir, "401", REJECTED_BODY)
    summary = tmp_path / "summary.md"
    branch = _git(repo, "rev-parse", "--abbrev-ref", "HEAD")

    result = _run(
        repo,
        bin_dir,
        summary,
        {var: f"dummy-{var.lower()}" for var in CREDENTIAL_VARS},
    )
    assert result.returncode == 1, result.stdout + result.stderr
    assert NO_VERDICT_ERROR in result.stdout, result.stdout
    for var in CREDENTIAL_VARS:
        assert f"Credential {var} rejected (HTTP 401)" in result.stderr, result.stderr
        # The API's own message is quoted so an exhausted cap reads as one.
        assert f"dummy-{var.lower()}" not in result.stderr, "credential value leaked"
    assert "invalid x-api-key" in result.stderr, result.stderr
    assert "5 configured credential rungs was rejected" in result.stderr, result.stderr
    assert _origin_head_subject(origin, branch) == "seed"


def test_an_open_release_pr_stands_the_run_down(tmp_path: Path) -> None:
    """A maintainer's release PR (release-prep.yaml) carries its own bump on a
    branch this run cannot see, so the fragments still read as pending here.
    Cutting now would be a second, colliding release."""
    repo, origin, _, bin_dir = _make_repo(tmp_path, FIXED_ONLY, open_release_pr="42")
    _install_curl_stub(bin_dir, "200", HEALTHY_BODY)
    summary = tmp_path / "summary.md"
    branch = _git(repo, "rev-parse", "--abbrev-ref", "HEAD")

    result = _run(repo, bin_dir, summary, {"ANTHROPIC_API_KEY": "sk-ant-api-dummy"})
    assert result.returncode == 0, result.stdout + result.stderr
    assert "A release PR is already open (#42)" in result.stdout
    assert _origin_head_subject(origin, branch) == "seed"


def test_a_refused_push_names_the_credential_and_stops(tmp_path: Path) -> None:
    """The branch rules on the default branch refuse a direct push. Every later
    attempt gets the same answer, so the script reports which grant is missing and
    stops. A real pre-receive hook on the bare origin produces the refusal."""
    repo, origin, _, bin_dir = _make_repo(tmp_path, FIXED_ONLY)
    _install_curl_stub(bin_dir, "200", HEALTHY_BODY)
    hook = origin / "hooks" / "pre-receive"
    _write_stub(
        hook,
        'echo "remote: GH006: Protected branch update failed for refs/heads/main." >&2\n'
        'echo "remote: error: Changes must be made through a pull request." >&2\n'
        "exit 1\n",
    )
    summary = tmp_path / "summary.md"
    branch = _git(repo, "rev-parse", "--abbrev-ref", "HEAD")

    result = _run(repo, bin_dir, summary, {"ANTHROPIC_API_KEY": "sk-ant-api-dummy"})
    assert result.returncode == 1, result.stdout + result.stderr
    assert "::error title=Release push denied::" in result.stdout
    assert "TEMPLATE_SYNC_TOKEN_ORG" in result.stderr, result.stderr
    assert "Release push to" not in result.stderr, "a refusal must not be retried"
    assert _origin_head_subject(origin, branch) == "seed"
    assert "Release blocked" in summary.read_text(encoding="utf-8")


def test_a_commit_that_landed_first_is_rebased_onto_and_pushed(tmp_path: Path) -> None:
    """Someone pushes to the branch between this run's checkout and its push. The
    first push is a non-fast-forward. The script rebases the release commit onto
    the new tip and pushes it, so both commits survive."""
    repo, origin, _, bin_dir = _make_repo(tmp_path, FIXED_ONLY)
    _install_curl_stub(bin_dir, "200", HEALTHY_BODY)
    summary = tmp_path / "summary.md"
    branch = _git(repo, "rev-parse", "--abbrev-ref", "HEAD")

    # A second clone lands a commit on origin first, touching a file the release
    # commit does not, so the rebase applies cleanly.
    other = tmp_path / "other"
    subprocess.run(
        ["git", "clone", "-q", "-b", branch, str(origin), str(other)],
        env=git_env(),
        check=True,
    )
    (other / "NOTES.md").write_text("concurrent work\n", encoding="utf-8")
    commit_all(other, "docs: concurrent work")
    _git(other, "push", "-q", "origin", branch)

    result = _run(repo, bin_dir, summary, {"ANTHROPIC_API_KEY": "sk-ant-api-dummy"})
    assert result.returncode == 0, result.stdout + result.stderr

    assert _origin_head_subject(origin, branch) == "chore(release): v1.0.1"
    subjects = _git(origin, "log", "--format=%s", branch).splitlines()
    assert subjects[:3] == [
        "chore(release): v1.0.1",
        "docs: concurrent work",
        "seed",
    ]
    assert "concurrent work" in _origin_file(origin, branch, "NOTES.md")
