"""Behavior tests for .github/scripts/release-readiness.sh credential degradation.

The load-bearing property: a total model-credential outage must NOT kill the run.
The script previously hard-required ANTHROPIC_API_KEY (`: "${ANTHROPIC_API_KEY:?…}"`)
and exited 1 on an HTTP 400/401/403, so one exhausted key stalled the whole release
pipeline. It now walks the credential ladder in bin/lib/release-model-call.bash and,
when every rung is missing or rejected, degrades to `bump_from_fragments` — announcing
that loudly on stdout, stderr, the job summary, and the PR body — and still opens the
release PR.

Everything here is asserted from observable behavior: exit code, stdout/stderr text,
the GITHUB_STEP_SUMMARY file, and the argv the stubbed `gh` was invoked with.
"""

import os
import shutil
import subprocess
from pathlib import Path

import pytest

from tests._helpers import REPO_ROOT, commit_all, git_env, init_test_repo

pytestmark = pytest.mark.skipif(
    (shutil.which("node") is None or shutil.which("jq") is None)
    and not os.environ.get("CI"),
    reason="node/jq not available (CI runners must have them: skipping there would silently drop this suite)",
)

CREDENTIAL_VARS = (
    "ANTHROPIC_API_KEY",
    "CLAUDE_CODE_OAUTH_TOKEN",
    "CLAUDE_CODE_OAUTH_TOKEN_FALLBACK",
    "CLAUDE_CODE_OAUTH_TOKEN_FALLBACK_3",
    "CLAUDE_CODE_OAUTH_TOKEN_FALLBACK_5",
)

DEGRADED_WARNING = "::warning title=Release readiness degraded::"

CHANGELOG = """# Changelog

## Unreleased

<!-- New releases are inserted below by scripts/assemble-changelog.mjs; do not edit this file by hand. -->

## [1.0.0] - 2025-01-01

### Added

- Initial release.
"""

# A well-formed Anthropic tool_use response: exactly the shape release-readiness.sh
# digs `should_release` / `recommended_bump` / `rationale` out of.
MODEL_RATIONALE = "Six user-facing fixes have piled up since the last tag."
HEALTHY_BODY = (
    '{"stop_reason":"tool_use","content":[{"type":"tool_use","name":"release_decision",'
    '"input":{"should_release":true,"recommended_bump":"patch","rationale":"'
    + MODEL_RATIONALE
    + '"}}]}'
)

REJECTED_BODY = (
    '{"error":{"type":"authentication_error","message":"invalid x-api-key"}}'
)

INVOCATION_SEP = "\x01"


def _write_stub(path: Path, body: str) -> None:
    path.write_text(f"#!/usr/bin/env bash\n{body}", encoding="utf-8")
    path.chmod(0o755)


def _install_gh_stub(bin_dir: Path, gh_log: Path) -> None:
    """A `gh` that records every invocation's argv (NUL-delimited, invocations
    separated by \\x01 — PR bodies are multi-line so newlines can't delimit) and
    behaves the way cut_release needs to reach `gh pr create`."""
    _write_stub(
        bin_dir / "gh",
        f'printf "%s\\0" "$@" >> "{gh_log}"\n'
        f'printf "{INVOCATION_SEP}" >> "{gh_log}"\n'
        'case "$1 $2" in\n'
        # No concurrent release PR: empty output means the stand-down probe passes.
        '"pr list") : ;;\n'
        '"pr create") echo "https://github.test/o/r/pull/7" ;;\n'
        "esac\n"
        "exit 0\n",
    )


def _install_curl_stub(bin_dir: Path, status: str, body: str) -> None:
    """A `curl` honouring `-o <file>` (where the response body lands) and printing
    the HTTP status on stdout — exactly what `-w "%{http_code}"` yields."""
    body_file = bin_dir / "curl_body.json"
    body_file.write_text(body, encoding="utf-8")
    _write_stub(
        bin_dir / "curl",
        "out=''\nprev=''\n"
        'for arg in "$@"; do\n'
        '  [[ "$prev" == "-o" ]] && out="$arg"\n'
        '  prev="$arg"\n'
        "done\n"
        f'[[ -n "$out" ]] && cat "{body_file}" > "$out"\n'
        f"printf '%s' '{status}'\n",
    )


def _make_repo(tmp_path: Path, fragments: dict[str, str]) -> tuple[Path, Path, Path]:
    """A sandbox repo carrying real copies of the script under test and everything
    it sources/executes, plus a bare origin. Returns (repo, gh_log, bin_dir)."""
    repo = tmp_path / "repo"
    init_test_repo(repo)

    scripts = repo / ".github" / "scripts"
    scripts.mkdir(parents=True)
    shutil.copy2(REPO_ROOT / ".github" / "scripts" / "release-readiness.sh", scripts)
    (scripts / "release-readiness.sh").chmod(0o755)

    (scripts / "lib").mkdir()
    shutil.copy2(
        REPO_ROOT / ".github" / "scripts" / "lib" / "retry.bash", scripts / "lib"
    )
    libdir = repo / "bin" / "lib"
    libdir.mkdir(parents=True)
    shutil.copy2(REPO_ROOT / "bin" / "lib" / "release-model-call.bash", libdir)

    (repo / "scripts").mkdir()
    shutil.copy2(REPO_ROOT / "scripts" / "assemble-changelog.mjs", repo / "scripts")
    shutil.copy2(REPO_ROOT / "scripts" / "pin-readme-rev.mjs", repo / "scripts")

    # A README with a consumer `rev:` pin, so the release path's pin step runs
    # for real here rather than taking its missing-file exit.
    (repo / "README.md").write_text(
        "# x\n\n```yaml\n- repo: x\n  rev: v1.0.0\n```\n", encoding="utf-8"
    )
    (repo / "package.json").write_text(
        '{"name": "x", "version": "1.0.0"}\n', encoding="utf-8"
    )
    (repo / "CHANGELOG.md").write_text(CHANGELOG, encoding="utf-8")
    fragdir = repo / "changelog.d"
    fragdir.mkdir()
    for name, text in fragments.items():
        (fragdir / name).write_text(text, encoding="utf-8")

    bare = tmp_path / "origin.git"
    subprocess.run(["git", "init", "-q", "--bare", str(bare)], check=True)
    commit_all(repo, "seed")
    subprocess.run(
        ["git", "remote", "add", "origin", str(bare)],
        cwd=repo,
        env=git_env(),
        check=True,
    )

    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    gh_log = tmp_path / "gh.log"
    _install_gh_stub(bin_dir, gh_log)
    return repo, gh_log, bin_dir


def _run(
    repo: Path, bin_dir: Path, summary: Path, credentials: dict[str, str]
) -> subprocess.CompletedProcess:
    env = git_env()
    for var in CREDENTIAL_VARS:
        env.pop(var, None)
    env.update(credentials)
    env["PATH"] = f"{bin_dir}:{env['PATH']}"
    env["GH_TOKEN"] = "gh-token-stub"
    env["GITHUB_STEP_SUMMARY"] = str(summary)
    # One attempt, no sleep: a rung must not be retried and no test may block.
    env["ANTHROPIC_MAX_ATTEMPTS"] = "1"
    env["ANTHROPIC_RETRY_DELAY"] = "0"
    # Never a real endpoint even if the stub were somehow bypassed.
    env["ANTHROPIC_API_URL"] = "https://api.invalid/v1/messages"
    return subprocess.run(
        ["bash", ".github/scripts/release-readiness.sh"],
        cwd=repo,
        env=env,
        capture_output=True,
        text=True,
    )


def _gh_invocations(gh_log: Path) -> list[list[str]]:
    if not gh_log.exists():
        return []
    calls = []
    for chunk in gh_log.read_text(encoding="utf-8").split(INVOCATION_SEP):
        if not chunk:
            continue
        args = [a for a in chunk.split("\0") if a != ""]
        if args:
            calls.append(args)
    return calls


def _pr_create_argv(gh_log: Path) -> list[str]:
    for argv in _gh_invocations(gh_log):
        if argv[:2] == ["pr", "create"]:
            return argv
    raise AssertionError(f"`gh pr create` was never invoked: {_gh_invocations(gh_log)}")


def _flag(argv: list[str], flag: str) -> str:
    return argv[argv.index(flag) + 1]


FIXED_ONLY = {"1.fixed.md": "- Fixed a crash.\n", "2.fixed.md": "- Fixed a typo.\n"}
WITH_ADDED = {"1.fixed.md": "- Fixed a crash.\n", "3.added.md": "- Added a flag.\n"}


def test_total_credential_outage_still_opens_release_pr(tmp_path: Path) -> None:
    """The regression this change exists to prevent: with NO credential set at all,
    the old script died at its `: "${ANTHROPIC_API_KEY:?…}"` guard and no release PR
    was ever cut. It must now degrade loudly and still open the PR."""
    repo, gh_log, bin_dir = _make_repo(tmp_path, FIXED_ONLY)
    _install_curl_stub(bin_dir, "401", REJECTED_BODY)  # never reached: no rung is set
    summary = tmp_path / "summary.md"

    result = _run(repo, bin_dir, summary, {})
    assert result.returncode == 0, result.stdout + result.stderr
    assert DEGRADED_WARNING in result.stdout, result.stdout
    assert "degraded to the deterministic bump floor" in result.stderr, result.stderr
    assert "No release credential is set" in result.stderr, result.stderr

    argv = _pr_create_argv(gh_log)
    assert "DEGRADED" in _flag(argv, "--body")

    summary_text = summary.read_text(encoding="utf-8")
    assert "> [!WARNING]" in summary_text, summary_text
    assert "degraded to the deterministic bump floor" in summary_text, summary_text


def test_every_rung_rejected_degrades_and_names_each_credential(
    tmp_path: Path,
) -> None:
    """All five rungs configured, every one 401'd. The run still cuts the PR, and
    the log accounts for each rejected rung BY VARIABLE NAME (never by value)."""
    repo, gh_log, bin_dir = _make_repo(tmp_path, FIXED_ONLY)
    _install_curl_stub(bin_dir, "401", REJECTED_BODY)
    summary = tmp_path / "summary.md"

    result = _run(
        repo,
        bin_dir,
        summary,
        {var: f"dummy-{var.lower()}" for var in CREDENTIAL_VARS},
    )
    assert result.returncode == 0, result.stdout + result.stderr
    assert DEGRADED_WARNING in result.stdout, result.stdout
    for var in CREDENTIAL_VARS:
        assert f"Credential {var} rejected (HTTP 401)" in result.stderr, result.stderr
        # The API's own message is quoted so an exhausted cap reads as one.
        assert f"dummy-{var.lower()}" not in result.stderr, "credential value leaked"
    assert "invalid x-api-key" in result.stderr, result.stderr
    assert "5 configured credential rungs was rejected" in result.stderr, result.stderr

    argv = _pr_create_argv(gh_log)
    assert "DEGRADED" in _flag(argv, "--body")
    assert "> [!WARNING]" in summary.read_text(encoding="utf-8")


@pytest.mark.parametrize(
    ("fragments", "expected_version"),
    [
        pytest.param(FIXED_ONLY, "1.0.1", id="fixed-only-takes-patch"),
        pytest.param(WITH_ADDED, "1.1.0", id="added-present-takes-minor"),
    ],
)
def test_degraded_bump_follows_fragment_categories(
    tmp_path: Path, fragments: dict[str, str], expected_version: str
) -> None:
    """The deterministic floor reads the semver signal off the fragment CATEGORIES:
    fixed/security leave the surface alone (patch), added/changed/removed/deprecated
    change it (minor). Asserted on the cut version in the real `gh pr create` argv."""
    repo, gh_log, bin_dir = _make_repo(tmp_path, fragments)
    _install_curl_stub(bin_dir, "401", REJECTED_BODY)
    summary = tmp_path / "summary.md"

    result = _run(repo, bin_dir, summary, {})
    assert result.returncode == 0, result.stdout + result.stderr

    argv = _pr_create_argv(gh_log)
    assert _flag(argv, "--title") == f"chore(release): v{expected_version}"

    branches = subprocess.run(
        ["git", "branch", "--list", f"auto-release/v{expected_version}"],
        cwd=repo,
        env=git_env(),
        capture_output=True,
        text=True,
        check=True,
    )
    assert f"auto-release/v{expected_version}" in branches.stdout


def test_healthy_first_rung_is_not_degraded(tmp_path: Path) -> None:
    """Non-vacuity pair for the degradation tests: a 200 with a well-formed verdict
    must produce NO degradation anywhere, and the PR body carries the model's own
    rationale. Without this, the tests above would pass on a script that always
    degrades."""
    repo, gh_log, bin_dir = _make_repo(tmp_path, FIXED_ONLY)
    _install_curl_stub(bin_dir, "200", HEALTHY_BODY)
    summary = tmp_path / "summary.md"

    result = _run(repo, bin_dir, summary, {"ANTHROPIC_API_KEY": "sk-ant-api-dummy"})
    assert result.returncode == 0, result.stdout + result.stderr
    assert "Model call succeeded on credential ANTHROPIC_API_KEY." in result.stderr

    summary_text = summary.read_text(encoding="utf-8")
    argv = _pr_create_argv(gh_log)
    body = _flag(argv, "--body")
    for surface in (result.stdout, result.stderr, summary_text, body):
        assert DEGRADED_WARNING not in surface
        assert "DEGRADED" not in surface
        assert "[!WARNING]" not in surface
        assert "deterministic bump floor" not in surface

    assert MODEL_RATIONALE in body
    assert MODEL_RATIONALE in summary_text
    assert _flag(argv, "--title") == "chore(release): v1.0.1"
